import type { Schema } from '../resource';
// @ts-ignore - Module is generated by Amplify at build time
import { env } from '$amplify/env/addUserToGroup';
import {
  AdminAddUserToGroupCommand,
  CognitoIdentityProviderClient,
} from '@aws-sdk/client-cognito-identity-provider';

type Handler = Schema['addUserToGroup']['functionHandler'];
const client = new CognitoIdentityProviderClient();

export const handler: Handler = async (event) => {
  const { userId, groupName } = event.arguments;

  // Safeguard: Ensure the environment variable is actually present
  if (!env.AMPLIFY_AUTH_USERPOOL_ID) {
    throw new Error('Missing UserPoolId environment variable.');
  }

  const command = new AdminAddUserToGroupCommand({
    Username: userId,
    GroupName: groupName,
    UserPoolId: env.AMPLIFY_AUTH_USERPOOL_ID,
  });

  try {
    const response = await client.send(command);
    return response;
  } catch (error: any) {
    console.error('Cognito Error:', error);
    throw error;
  }
};
